name: Build Vite Microfrontends

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm globally via npm
        run: npm install -g pnpm

      - name: Check pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build host
        working-directory: ./apps/host
        run: pnpm install && pnpm build

      - name: Build remote
        working-directory: ./apps/remote
        run: pnpm install && pnpm build

      - name: Prepare deployment
        run: |
          mkdir -p dist
          cp -r apps/host/dist dist/host
          cp -r apps/remote/dist dist/remote

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

