name: Build Vite Microfrontends

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js with Corepack
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.6 --activate # можно заменить на твою версию

      - name: Verify pnpm installed
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build Host App
        run: pnpm --filter host run build

      - name: Build Remote App
        run: pnpm --filter remote run build
