name: Build Vite Microfrontends

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm globally via npm
        run: |
          npm install -g pnpm
          echo "::add-path::$(npm bin -g)"

      - name: Check pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build Remote App
        run: pnpm --filter remote run build

      - name: Build Host App
        run: pnpm --filter host run build
